name: DeathSwap
version: '${project.version}'
main: com.bigbolev2.plugins.DeathSwap
api-version: 1.18
authors: [ bigbolev2 ]
description: A many-player game to kill each other via traps!
commands:
  deathswap:
    description: The main command for DeathSwap